name: ml4t
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - quantopian
dependencies:
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.3.0
  - absl-py=0.7.0
  - appdirs=1.4.3
  - args=0.1.0
  - arrow-cpp=0.13.0
  - asn1crypto=0.24.0
  - astor=0.7.1
  - atk=2.25.90
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - automat=0.7.0
  - autopep8=1.4.3
  - backcall=0.1.0
  - beautifulsoup4=4.7.1
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - blas=1.1
  - bleach=3.1.0
  - blosc=1.15.0
  - bokeh=1.1.0
  - boost-cpp=1.68.0
  - boto=2.49.0
  - boto3=1.9.111
  - botocore=1.12.112
  - bottleneck=1.2.1
  - brotli=1.0.7
  - bz2file=0.98
  - bzip2=1.0.6
  - c-ares=1.15.0
  - ca-certificates=2019.3.9
  - cachetools=3.1.0
  - cairo=1.14.12
  - catboost=0.14.2
  - certifi=2019.3.9
  - cffi=1.12.2
  - chardet=3.0.4
  - cld2-cffi=0.1.4
  - clint=0.5.1
  - cloudpickle=0.8.1
  - colorlover=0.3.0
  - constantly=15.1.0
  - cryptography=2.6.1
  - cssselect=1.0.3
  - cudatoolkit=10.0.130
  - cudnn=7.3.1
  - cycler=0.10.0
  - cymem=2.0.2
  - cython=0.29.7
  - cytoolz=0.9.0.1
  - dask-core=1.2.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - dill=0.2.9
  - docutils=0.14
  - empyrical=0.3.4
  - entrypoints=0.3
  - expat=2.2.6
  - fastcache=1.0.2
  - fastparquet=0.2.1
  - ffmpeg=4.1.1
  - fontconfig=2.13.1
  - freeglut=3.0.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - ftfy=4.4.3
  - funcy=1.12
  - furl=2.0.0
  - future=0.17.1
  - gast=0.2.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gdk-pixbuf=2.36.12
  - gensim=3.7.1
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.1.4
  - glib=2.56.2
  - glog=0.3.5
  - gmp=6.1.2
  - gmpy2=2.0.8
  - gnutls=3.6.5
  - gobject-introspection=1.56.1
  - graphite2=1.3.13
  - graphviz=2.38.0
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gtk2=2.24.31
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.9.0
  - harfbuzz=1.9.0
  - hdbscan=0.8.20
  - hdf5=1.10.4
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.8
  - ijson=2.3
  - imageio=2.5.0
  - incremental=17.5.0
  - inflection=0.3.1
  - intel-openmp=2019.3
  - ipydatawidgets=4.0.0
  - ipykernel=5.1.0
  - ipyscales=0.3.0
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - ipyvolume=0.5.1
  - ipywebrtc=0.4.3
  - ipywidgets=7.4.2
  - jasper=1.900.1
  - jedi=0.13.3
  - jinja2=2.10.1
  - jmespath=0.9.4
  - joblib=0.12.5
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - keras=2.2.4
  - keras-applications=1.0.7
  - keras-base=2.2.4
  - keras-preprocessing=1.0.9
  - kiwisolver=1.0.1
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libevent=2.1.8
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libgpuarray=0.7.6
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.3
  - libopus=1.3
  - libpng=1.6.36
  - libprotobuf=3.7.1
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libvpx=1.7.0
  - libwebp=1.0.1
  - libxcb=1.13
  - libxgboost=0.82
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lightgbm=2.2.1
  - llvmlite=0.28.0
  - lxml=4.3.3
  - lz4-c=1.8.3
  - lzo=2.10
  - markdown=3.0.1
  - markupsafe=1.1.1
  - matplotlib=2.2.2
  - mistune=0.8.4
  - mkl=2019.3
  - mkl-service=1.1.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - mock=2.0.0
  - more-itertools=6.0.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - msgpack-numpy=0.4.3.2
  - msgpack-python=0.6.1
  - murmurhash=1.0.2
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nettle=3.4.1
  - networkx=2.3
  - ninja=1.9.0
  - nltk=3.4
  - notebook=5.7.8
  - numba=0.43.1
  - numexpr=2.6.9
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openblas=0.3.3
  - opencv=3.4.4
  - openh264=1.8.0
  - openssl=1.1.1b
  - orderedmultidict=1.0
  - packaging=19.0
  - pandas=0.24.2
  - pandas-datareader=0.7.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parquet-cpp=1.5.1
  - parsel=1.5.1
  - parso=0.4.0
  - patsy=0.5.1
  - pbr=5.1.3
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.0.3
  - pixman=0.34.0
  - plac=0.9.6
  - plotly=3.7.0
  - pluggy=0.9.0
  - preshed=2.0.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - protobuf=3.7.1
  - ptyprocess=0.6.0
  - py=1.8.0
  - py-xgboost=0.82
  - pyarrow=0.13.0
  - pyasn1=0.4.5
  - pyasn1-modules=0.2.4
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pydispatcher=2.0.5
  - pydot=1.4.1
  - pyemd=0.5.1
  - pyfinance=1.2.5
  - pyfolio=0.8.0
  - pygments=2.3.1
  - pygpu=0.7.6
  - pyhamcrest=1.9.0
  - pyldavis=2.1.2
  - pymc3=3.6
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyphen=0.9.5
  - pyqt=5.6.0
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - pytables=3.5.1
  - pytest=4.4.0
  - pytest-runner=4.4
  - python=3.6.8
  - python-dateutil=2.8.0
  - python-graphviz=0.8.4
  - python-levenshtein=0.12.0
  - python-snappy=0.5.3
  - pythreejs=2.0.2
  - pytorch=1.0.1
  - pytz=2019.1
  - pywavelets=1.0.3
  - pyyaml=5.1
  - pyzmq=18.0.0
  - qt=5.6.3
  - qtconsole=4.4.3
  - quandl=3.4.5
  - queuelib=1.5.0
  - re2=2019.04.01
  - readline=7.0
  - regex=2019.03.09
  - requests=2.21.0
  - retrying=1.3.3
  - s3transfer=0.2.0
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - scikit-optimize=0.5.2
  - scipy=1.2.1
  - scrapy=1.5.2
  - seaborn=0.9.0
  - selenium=3.141.0
  - send2trash=1.5.0
  - service_identity=18.1.0
  - setuptools=41.0.0
  - shap=0.28.5
  - sip=4.18.1
  - six=1.12.0
  - smart_open=1.8.0
  - snappy=1.1.7
  - soupsieve=1.8
  - spacy=2.0.16
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - sympy=1.4
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - terminado=0.8.2
  - testpath=0.4.2
  - textacy=0.6.2
  - textblob=0.15.3
  - theano=1.0.4
  - thinc=6.12.1
  - thrift=0.11.0
  - thrift-cpp=0.12.0
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=6.0.2
  - tqdm=4.31.1
  - traitlets=4.3.2
  - traittypes=0.2.1
  - twisted=18.9.0
  - ujson=1.35
  - umap-learn=0.3.8
  - unidecode=1.0.23
  - urllib3=1.24.1
  - w3lib=1.20.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.2
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - wordcloud=1.5.0
  - wrapt=1.10.11
  - x264=1!152.20180806
  - xgboost=0.82
  - xlrd=1.2.0
  - xmltodict=0.12.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.6.0
  - zstd=1.3.3
  - pip:
    - box2d-py==2.3.8
    - en-core-web-sm==2.0.0
    - es-core-news-sm==2.0.0
    - gym==0.12.1
    - mako==1.0.7
    - pyglet==1.3.2
    - pymdptoolbox==4.0b3

